import { getAuthErrorMessage, observeAuthState, sendPasswordReset, signOut } from "./auth.js";
import { getProfile } from "./profile.js";

const drawerMarkup = `<aside class="account-drawer is-guest" data-account-drawer aria-label="Account menu" aria-hidden="true"><div class="drawer-head"><div class="drawer-profile"><div class="drawer-avatar" data-profile-avatar>AM</div><div><strong data-profile-name>Account</strong><small data-profile-email></small></div></div><button class="icon-button" type="button" data-account-action="close" aria-label="Close account menu">&times;</button></div><nav class="drawer-nav"><a class="auth-only" href="profile.html"><span>Profile</span><small>Personal details and picture</small></a><a class="auth-only" href="profile.html#settings"><span>Settings</span><small>Password and preferences</small></a><a class="auth-only" href="vault.html"><span>Purchased items</span><small>Receipts and warranties</small></a><a class="auth-only" href="qr-vault.html"><span>QR vault</span><small>Saved and generated codes</small></a></nav><div class="drawer-footer"><button class="drawer-link auth-only" type="button" data-account-action="reset"><span>Forgot password</span><small>Send a secure reset email</small></button><button class="drawer-link guest-only drawer-login" type="button" data-account-action="login">Log in</button><button class="drawer-link auth-only drawer-logout" type="button" data-account-action="logout">Log out</button></div></aside><div class="drawer-scrim" data-account-action="close"></div><div class="account-toast" data-account-toast role="status" aria-live="polite"></div>`;

function toast(message) { const element = document.querySelector("[data-account-toast]"); element.textContent = message; element.classList.add("is-visible"); clearTimeout(toast.timer); toast.timer = setTimeout(() => element.classList.remove("is-visible"), 3200); }
function initials(profile) { return (profile?.displayName || "AM").split(/\s+/).map((part) => part[0]).join("").slice(0, 2).toUpperCase(); }
function setDrawer(open) { const drawer = document.querySelector("[data-account-drawer]"); if (!drawer) return; drawer.classList.toggle("is-open", open); drawer.setAttribute("aria-hidden", String(!open)); document.body.classList.toggle("drawer-open", open); }
function updateIdentity(profile) { document.querySelectorAll("[data-profile-avatar]").forEach((element) => { element.textContent = initials(profile); if (profile?.photoData) { element.textContent = ""; element.style.backgroundImage = `url(${profile.photoData})`; } }); document.querySelectorAll("[data-profile-name]").forEach((element) => { element.textContent = profile?.displayName || "Account"; }); document.querySelectorAll("[data-profile-email]").forEach((element) => { element.textContent = profile?.email || ""; }); document.querySelectorAll(".avatar-button").forEach((element) => { element.textContent = initials(profile); if (profile?.photoData) { element.textContent = ""; element.style.backgroundImage = `url(${profile.photoData})`; element.classList.add("has-photo"); } }); }

document.body.insertAdjacentHTML("beforeend", drawerMarkup);
document.querySelectorAll(".avatar-button").forEach((button) => { button.addEventListener("click", (event) => { event.preventDefault(); setDrawer(true); }); });
document.addEventListener("click", async (event) => { const action = event.target.closest("[data-account-action]")?.dataset.accountAction; if (!action) return; if (action === "close") setDrawer(false); if (action === "login") { setDrawer(false); const modal = document.querySelector("[data-modal='auth']"); if (modal) modal.showModal(); } if (action === "logout") { await signOut(); setDrawer(false); window.location.href = "index.html"; } if (action === "reset") { const email = document.querySelector("[data-profile-email]")?.textContent; if (!email) { toast("Sign in with an email account first."); return; } try { await sendPasswordReset(email); toast("Password reset email sent."); } catch (error) { toast(getAuthErrorMessage(error)); } } });
observeAuthState(async (user) => { const drawer = document.querySelector("[data-account-drawer]"); drawer?.classList.toggle("is-authenticated", Boolean(user)); drawer?.classList.toggle("is-guest", !user); document.querySelectorAll(".auth-only").forEach((element) => { element.hidden = !user; }); document.querySelectorAll(".guest-only").forEach((element) => { element.hidden = Boolean(user); }); if (user) updateIdentity(await getProfile(user)); });